apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
<<<<<<< HEAD
    - forum-aks.hackathonshift.com.br
    secretName: tls-secret
  rules:
  - host: forum-aks.hackathonshift.com.br
=======
    - forum.hackathonshift.com.br
    secretName: prod-forum-secret
  rules:
  - host: forum.hackathonshift.com.br 
>>>>>>> a35d40c5c8d719a13e2a4b16a744a29fbb9b1ee4
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80
  